/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '11/9/19 5:26 PM' with Gradle 3.0
 *
 * @author Administrator, @date 11/9/19 5:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
