CREATE TABLE MASTER(
NAME VARCHAR(20),
PASSWORD VARCHAR(20),
BALANCE DOUBLE,
PRIMARY KEY(NAME)
);

create TABLE TRANSACTION(
NAME VARCHAR(20),
AMOUNT DOUBLE,
TYPE VARCHAR(20),
DATE DATE,
FOREIGN KEY(NAME) REFERENCES MASTER(NAME)
);


INSERT INTO MASTER(NAME,PASSWORD,BALANCE)
VALUES('NILAM','NIL',500);

INSERT INTO TRANSACTION(NAME,AMOUNT,TYPE,DATE)
VALUES('Komal',3000,'DEPOSITE','2019-11-5');

SELECT * FROM MASTER;
SELECT * FROM TRANSACTION;

SELECT EXISTS(SELECT * from master WHERE name='nilam' and password='nil');

INSERT INTO MASTER(NAME,PASSWORD,BALANCE)
VALUES('NILAM','345',500);


UPDATE MASTER SET BALANCE=2300 WHERE NAME='KOMAL';
INSERT INTO TRANSACTION(NAME,AMOUNT,TYPE,DATE)
VALUES('Komal', 700,'WITHDRAW','2019-11-6'); 
SELECT * FROM MASTER;
SELECT * FROM TRANSACTION;

DELETE FROM TRANSACTION WHERE NAME= 'Komal';
