CREATE TABLE CONTACT(
ID INT AUTO_INCREMENT ,
FIRSTNAME VARCHAR(30),
LASTNAME VARCHAR(35),
PHONENO INT NOT NULL,
EMAILID VARCHAR(30),
PRIMARY KEY(ID)
);

SELECT * FROM CONTACT;

insert INTO CONTACT(FIRSTNAME,LASTNAME,PHONENO,EMAILID)
VALUES("NIKI","PATEL",48584,"DHH@GMAIL.COM");


insert INTO CONTACT(FIRSTNAME,LASTNAME,PHONENO,EMAILID)
VALUES("NILAM","PATEL",983435554,"NIL@GMAIL.COM");
SELECT * FROM CONTACT;