CREATE TABLE CUSTMR(
CUSTOMERID INT,
NAME VARCHAR(20),
BALANCE INT,
PRIMARY KEY(CUSTOMERID)
);

CREATE TABLE MERCHANT(
ID INT,
NAME VARCHAR(20),
CUSTOMERID INT,
BALANCE INT,
PRIMARY KEY(ID),
FOREIGN KEY(CUSTOMERID) REFERENCES CUSTMR(CUSTOMERID)
);


INSERT INTO CUSTMR(CUSTOMERID,NAME,BALANCE)
VALUES(101,'NILAM',25000);


INSERT INTO MERCHANT(ID,NAME,CUSTOMERID,BALANCE)

select * from CUSTMR;
SELECT * FROM MERCHANT;
