CREATE TABLE DEPT (
 DEPTNO INT NOT NULL,
 DNAME varchar(14),
 LOC varchar(13),
PRIMARY KEY (DEPTNO));

INSERT INTO DEPT(DEPTNO,DNAME,LOC)
VALUES (10,'ACCOUNTING','NEW YORK');
 
INSERT INTO DEPT(DEPTNO,DNAME,LOC) VALUES (20,'RESEARCH','DALLAS');
INSERT INTO DEPT(DEPTNO,DNAME,LOC) VALUES (30,'SALES','CHICAGO');
INSERT INTO DEPT(DEPTNO,DNAME,LOC) VALUES (40,'OPERATIONS','BOSTON');
 
 DROP TABLE EMP;
CREATE TABLE EMP (
 EMPNO INT NOT NULL,
 ENAME varchar(10),
 JOB   varchar(9),
 MGR   INT REFERENCES EMP(EMPNO),
 HIREDATE DATE,
 SAL DECIMAL(10,2),
 COMM DECIMAL(10,2),
 DEPTNO INT NOT NULL,
 FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO),
 PRIMARY KEY (EMPNO));
 
 INSERT INTO EMP VALUES (7839,'KING','PRESIDENT',NULL,'81-11-17',5000,NULL,10);
INSERT INTO EMP VALUES (7698,'BLAKE','MANAGER',7839,'81-5-1',2850,NULL,30);
INSERT INTO EMP VALUES (7782,'CLARK','MANAGER',7839,'81-6-9',2450,NULL,10);
INSERT INTO EMP VALUES (7566,'JONES','MANAGER',7839,'81-4-2',2975,NULL,20);
INSERT INTO EMP VALUES (7654,'MARTIN','SALESMAN',7698,'81-9-28',1250,1400,30);
INSERT INTO EMP VALUES (7499,'ALLEN','SALESMAN',7698,'81-2-20',1600,300,30);
INSERT INTO EMP VALUES (7844,'TURNER','SALESMAN',7698,'81-9-8',1500,0,30);
INSERT INTO EMP VALUES (7900,'JAMES','CLERK',7698,'81-12-3',950,NULL,30);
INSERT INTO EMP VALUES (7521,'WARD','SALESMAN',7698,'81-2-22',1250,500,30);
INSERT INTO EMP VALUES (7902,'FORD','ANALYST',7566,'81-12-3',3000,NULL,20);
INSERT INTO EMP VALUES (7369,'SMITH','CLERK',7902,'80-12-17',800,NULL,20);
INSERT INTO EMP VALUES (7788,'SCOTT','ANALYST',7566,'82-12-09',3000,NULL,20);
INSERT INTO EMP VALUES (7876,'ADAMS','CLERK',7788,'83-1-12',1100,NULL,20);
INSERT INTO EMP VALUES (7934,'MILLER','CLERK',7782,'83-1-23',1300,NULL,10);
select * from DEPT;
SELECT * FROM EMP;

SELECT ENAME 
FROM EMP 
ORDER BY ENAME;

SELECT *
FROM EMP 
ORDER BY SAL DESC;

SELECT ENAME,SAL
FROM EMP
WHERE DEPTNO=10;

SELECT * 
FROM EMP 
WHERE SAL BETWEEN 1000 AND 5000;

SELECT * 	
FROM EMP
WHERE DEPTNO=10 OR DEPTNO=20;

SELECT * 
FROM EMP
WHERE COMM IS NULL;

SELECT * 
FROM EMP
WHERE JOB="MANAGER";

SELECT EMPNO,ENAME,(SAL*12+IFNULL (COMM,0))"ANNUAL CTC"
FROM EMP;

SELECT EMPNO,ENAME,HIREDATE,CURRENT_DATE "CURRENT_DATE",DATEDIFF(CURRENT_DATE,HIREDATE)/365"TENURE"
FROM EMP;

SELECT * FROM EMP
WHERE ENAME='SCOTT';

--SUB QUERIES

SELECT ENAME,SAL
FROM EMP 
WHERE SAL=(SELECT SAL FROM EMP
				WHERE ENAME='SCOTT');

SELECT ENAME,JOB,SAL
FROM EMP
WHERE JOB=(SELECT JOB FROM EMP
				WHERE ENAME='SMITH');

SELECT * FROM EMP
ORDER BY ENAME;
SELECT * FROM DEPT;

--JOINS

SELECT EMP.ENAME, DEPT.DNAME
FROM EMP
INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;

SELECT EMP.ENAME, DEPT.DNAME, EMP.DEPTNO
FROM DEPT
LEFT JOIN EMP ON EMP.DEPTNO = DEPT.DEPTNO;

SELECT DEPT.DNAME, DEPT.DEPTNO
FROM EMP
RIGHT JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE EMP.ENAME IS NULL

SELECT X.ENAME AS ENAME, Y.ENAME AS BOSSNAME, X.JOB, Y.JOB
FROM EMP X
INNER JOIN EMP Y ON X.MGR = Y.EMPNO
ORDER BY X.ENAME;

SELECT X.ENAME AS ENAME, Y.ENAME AS BOSSNAME, X.JOB, Y.JOB
FROM EMP X
LEFT JOIN EMP Y ON X.MGR = Y.EMPNO
WHERE Y.ENAME IS NULL
ORDER BY X.ENAME;

SELECT X.ENAME AS ENAME, Y.ENAME AS BOSSNAME,DEPT.DNAME
FROM EMP X
LEFT JOIN EMP Y ON X.MGR = Y.EMPNO
LEFT JOIN DEPT ON X.DEPTNO = DEPT.DEPTNO;

--AGGREGATION

SELECT COUNT(EMPNO)
FROM EMP;

SELECT SUM(SAL)
FROM EMP;

SELECT AVG(SAL)
FROM EMP;

SELECT ENAME, SAL
FROM EMP
ORDER BY SAL DESC
LIMIT 3;

--AGGREGATE FUNCTION  + COLUMNS
SELECT COUNT(EMPNO),DEPTNO
FROM EMP
WHERE DEPTNO=10;

SELECT COUNT(EMPNO),DEPTNO
FROM EMP
GROUP BY DEPTNO;

SELECT COUNT(*), JOB
FROM EMP
GROUP BY JOB
ORDER BY JOB;

SELECT COUNT(*), JOB, DEPTNO
FROM EMP
GROUP BY DEPTNO, JOB;

SELECT COUNT(*) AS COUNT, JOB
FROM EMP
GROUP BY JOB
HAVING COUNT > 2
ORDER BY JOB DESC;

SELECT COUNT(*) AS COUNT, JOB
FROM EMP
WHERE DEPTNO=10 OR DEPTNO=20
GROUP BY JOB
HAVING COUNT > 1
ORDER BY COUNT DESC;

SELECT * FROM EMP;











